[package]
name = "todo_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
deser = { version = "0.8.0", features = ["derive"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "3.0.0"
uuid = { version = "1.4", features = ["v4"] }
